export const enum TradeQueryKeys {
  GET_CASH_BALANCE = 'TRADE/GET_CASH_BALANCE',
  GET_COIN_ASSET = 'TRADE/GET_COIN_ASSET',
  CREATE_BUY_ORDER = 'TRADE/CREATE_BUY_ORDER',
  CREATE_SELL_ORDER = 'TRADE/CREATE_SELL_ORDER',
  ADD_CASH_TO_TRADE = 'TRADE/ADD_CASH_TO_TRADE',
  RESET_PORTFOLIO = 'TRADE/RESET_PORTFOLIO',
}