import { Anuphan } from 'next/font/google'
import type { Metadata } from 'next'
import './globals.css'
import { BalanceProvider } from '@/components/contexts/BalanceContext'


const anuphan = Anuphan({
  weight: '400',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Test NextJS',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={anuphan.className}>
      <body>
        <BalanceProvider>
          {children}
        </BalanceProvider>
      </body>
    </html>
  )
}
